name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: update
      run: apt-get update
    - name: sbcl install
      run: apt-get install sbcl
    - name: configure and build
      run: ./configure && sbcl --load make.lisp
